package com.ltu.fm.model.device;

import java.util.Date;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.ltu.fm.configuration.DynamoDBConfiguration;
import com.ltu.fm.utils.AppUtil;

/**
 * The Class Device.
 */
@DynamoDBTable(tableName = DynamoDBConfiguration.DEVICE_TABLE_NAME)
public class Device {

	/** The id. */
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	/** The phone id. */
	@DynamoDBAttribute(attributeName = "phoneId")
	private String phoneId;
	
	/** The type. IOS/ANDROID*/
	@DynamoDBAttribute(attributeName = "type")
	private String type;
	
	/** The push token. */
	@DynamoDBAttribute(attributeName = "pushToken")
	private String pushToken;

	/** The last login user id. */
	@DynamoDBAttribute(attributeName = "lastLoginUserId")
	private String lastLoginUserId;
	
	/** The created at. */
	@DynamoDBAttribute(attributeName = "createdAt")
	private Date createdAt;

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the phone id.
	 *
	 * @return the phone id
	 */
	public String getPhoneId() {
		return phoneId;
	}

	/**
	 * Sets the phone id.
	 *
	 * @param phoneId the new phone id
	 */
	public void setPhoneId(String phoneId) {
		this.phoneId = phoneId;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Gets the push token.
	 *
	 * @return the push token
	 */
	public String getPushToken() {
		return pushToken;
	}

	/**
	 * Sets the push token.
	 *
	 * @param pushToken the new push token
	 */
	public void setPushToken(String pushToken) {
		this.pushToken = pushToken;
	}

	/**
	 * Gets the last login user id.
	 *
	 * @return the last login user id
	 */
	public String getLastLoginUserId() {
		return lastLoginUserId;
	}

	/**
	 * Sets the last login user id.
	 *
	 * @param lastLoginUserId the new last login user id
	 */
	public void setLastLoginUserId(String lastLoginUserId) {
		this.lastLoginUserId = lastLoginUserId;
	}

	/**
	 * Gets the created at.
	 *
	 * @return the created at
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * Sets the created at.
	 *
	 * @param createdAt the new created at
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * Instantiates a new device.
	 */
	public Device() {
		
	}
	
	/**
	 * Instantiates a new device.
	 *
	 * @param id the id
	 * @param phoneId the phone id
	 * @param type the type
	 * @param pushToken the push token
	 * @param lastLoginUserId the last login user id
	 */
	public Device(String id, String phoneId, String type, String pushToken, String lastLoginUserId) {
		this.id = id;
		this.phoneId = phoneId;
		this.type = type;
		this.pushToken = pushToken;
		this.lastLoginUserId = lastLoginUserId;
	}
	
	/**
	 * Instantiates a new device.
	 *
	 * @param phoneId the phone id
	 * @param type the type
	 * @param pushToken the push token
	 * @param lastLoginUserId the last login user id
	 */
	public Device(String phoneId, String type, String pushToken, String lastLoginUserId) {
		this.phoneId = phoneId;
		this.type = type;
		this.pushToken = pushToken;
		this.lastLoginUserId = lastLoginUserId;
	}
	
	/**
	 * Instantiates a new device.
	 *
	 * @param item the item
	 */
	public Device(Map<String, AttributeValue> item) {
		try {
			this.id = item.get("id").getS();
			this.phoneId = item.get("phoneId").getS();
			this.type = item.get("type").getS();
			this.pushToken = item.get("pushToken").getS();
			this.createdAt = item.get("createdAt") != null ? AppUtil.toDate(item
					.get("createdAt").getS()) : null;
		} catch (Exception e) {
			//log.error(e.getMessage(), e.getCause());
			//FIXME Phu
		}
	}
	
}
